name: bionmed_app
version: 1.2.4+24
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.5.3+2
  google_fonts: ^3.0.1
  flutter_launcher_icons: ^0.11.0
  intl: ^0.17.0
  carousel_slider: ^4.1.1
  intl_phone_number_input: ^0.7.0+2
  flutter_spinkit: ^5.1.0
  lottie: ^1.4.2
  loading_overlay: ^0.3.0
  platform_device_id: ^1.0.1
  image_picker: ^0.8.5+3
  get_storage: ^2.0.3
  location: ^4.4.0
  geocoding: ^2.0.5
  permission_handler: ^10.0.0
  cached_network_image: ^3.2.1
  dotted_line: ^3.1.0
  dotted_border: ^2.0.0+3
  url_launcher: ^6.1.10
  accordion: ^2.5.1
  flutter_easyloading: ^3.0.5
  rating_dialog: ^2.0.4
  firebase_messaging: ^14.1.3
  flutter_countdown_timer: ^4.1.0
  file_picker: ^5.2.4
  flutter_chat_types: ^3.6.0
  mime: ^1.0.3
  open_filex: ^4.3.2
  flutter_chat_ui: ^1.6.6
  get: ^4.6.5
  zego_uikit_prebuilt_call: ^3.12.0
  #  zego_zim: ^2.5.0+1
  zego_uikit_signaling_plugin: ^2.2.1
  flutter_styled_toast: ^2.1.3
  draggable_fab: ^0.1.4
  flutter_time_picker_spinner: 2.0.0
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  cloud_firestore: ^4.3.2
  assets_audio_player: ^3.0.6
  google_maps_flutter: 2.2.3
  geolocator: 9.0.2
  search_map_location: 0.0.6
  search_map_place_updated: 0.0.4
  gallery_saver: ^2.3.2
  flutter_callkit_incoming: ^2.0.0
  awesome_notifications: ^0.7.4+1
  flutter_email_sender: ^5.2.0
  flutter_phone_direct_caller: ^2.1.1
  flutter_html: ^3.0.0-alpha.6
  photo_view: ^0.14.0
  timezone: ^0.9.1
  avatar_glow: ^2.0.2
  flutter_rating_bar: ^4.0.1
  zego_zimkit: ^1.7.0
  flutter: 
    sdk: flutter


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_icons: 
  image_path_ios: assets/images/logo-bionmed.png
  image_path_android: assets/images/logo-bionmed.png
  image_path: assets/images/logo-bionmed.png
  android: true
  ios: true

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
    - assets/json/
    - assets/ringtone/
  fonts: 
    - family: Ubuntu
      fonts: 
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 500
  uses-material-design: true

